// redux.action定義一覧
export const ActionTypes = {
    GET_PREFECTURE: "GET_PREFECTURE",
    GET_PREFECTURE_OK: "GET_PREFECTURE_OK",
    GET_PREFECTURE_NG: "GET_PREFECTURE_NG",
    GET_POPULATION: "GET_POPULATION",
    GET_POPULATION_OK: "GET_POPULATION_OK",
    GET_POPULATION_NG: "GET_POPULATION_NG"
}


